Config:
    Gateway:
        GRPCEndpointHost: "aruna-server-service"
        GRPCEndpointPort: 9090
    Swagger:
        Path: "www/swagger"
    Server:
        Port: 8080
        BaseUrl: "https://localhost"
    KeyCloak:
        Url: "keycloak.localhost"
        ClientId: "XXXXXX"
        Secret: "XXXXX"